// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/shutdown": {
            "get": {
                "description": "Shut the server down in case of when the application is running in background",
                "consumes": [
                    "application/json",
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "application/json"
                ],
                "tags": [
                    "Wipe"
                ],
                "summary": "Shut the server down",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/software": {
            "get": {
                "description": "List details of all software",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Software"
                ],
                "summary": "List details of all software",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Software"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new software entry with the input paylod",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Software"
                ],
                "summary": "Create a new software entry",
                "parameters": [
                    {
                        "description": "Create software",
                        "name": "software",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Software"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Software"
                        }
                    }
                }
            }
        },
        "/software/{id}": {
            "put": {
                "description": "Update the software corresponding to the input id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Software"
                ],
                "summary": "Update software identified by the given id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the software to be updated",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated software",
                        "name": "software",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Software"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Software"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete the software corresponding to the input id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Software"
                ],
                "summary": "Delete software identified by the given id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the software to be deleted",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    }
                }
            }
        },
        "/software/{name}": {
            "get": {
                "description": "Get details of software corresponding to the input software name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Software"
                ],
                "summary": "Get details for a given software name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Name of the software",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Software"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Software": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Web Browser"
                },
                "homepage": {
                    "type": "string",
                    "example": "https://www.google.com/intl/de/chrome/"
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "license": {
                    "type": "string",
                    "example": "MIT"
                },
                "name": {
                    "type": "string",
                    "example": "Google Chrome"
                },
                "version": {
                    "type": "string",
                    "example": "1.0"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Software-Database API",
	Description: "This is the API for the TEKO Software Database Project",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
